import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      // Generated by `npx cap add`. Each contains a copy of the built web
      // bundle, and flat config does not read .gitignore, so without these
      // `npm run lint` reports ~100 errors from minified vendor output.
      "android/**",
      "ios/**",
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
