/**
 * Governance vocabulary worth marking in body copy.
 *
 * Kept as content rather than styling so no question is ever hand-decorated —
 * `<ConceptHighlight>` reads this list, and adding a term marks it everywhere
 * at once.
 *
 * Two rules keep highlighting useful rather than decorative:
 *
 *  - Only terms of art. A phrase earns a place here if a practitioner would
 *    recognise it as a named concept with obligations attached, not because it
 *    sounds important. "Impact assessment" qualifies; "organisation" does not.
 *  - Longest match wins, so "AI impact assessment" is marked once rather than
 *    as three fragments.
 *
 * The renderer caps how many marks appear in one block. A paragraph where
 * every other phrase is highlighted reads as noise, and nothing stands out.
 */
export const CONCEPT_TERMS: string[] = [
  // Frameworks and instruments
  "AI impact assessment",
  "impact assessment",
  "conformity assessment",
  "privacy impact assessment",
  "data protection impact assessment",
  "algorithmic impact assessment",
  "NIST AI Risk Management Framework",
  "AI Risk Management Framework",
  "NIST AI RMF",
  "NIST ARIA",
  "EU AI Act",
  "ISO/IEC 42001",
  "ISO 42001",
  "OECD AI Principles",
  "GDPR",
  "HIPAA",
  "CCPA",
  "Title VII",
  "civil rights",
  "civil-rights",
  "AI management system",
  "AI governance program",
  "governance framework",
  "regulatory sandbox",
  "AI inventory",
  "use case inventory",
  "body of knowledge",
  "exam blueprint",

  // Lifecycle and development
  "data governance",
  "data lineage",
  "data provenance",
  "data minimization",
  "data minimisation",
  "privacy by design",
  "purpose limitation",
  "lawful basis",
  "legitimate interest",
  "informed consent",
  "data subject rights",
  "data subject",
  "differential privacy",
  "de-identification",
  "de-identified",
  "re-identification",
  "expert determination",
  "limited data set",
  "minimum necessary",
  "protected health information",
  "personally identifiable information",
  "synthetic data",
  "feature engineering",
  "training data",
  "test set",
  "overfitting",
  "model card",
  "technical documentation",
  "red teaming",
  "red-teaming",
  "threat modelling",
  "threat modeling",
  "adversarial testing",
  "bias testing",
  "bias audit",
  "fairness evaluation",
  "model validation",
  "model drift",
  "data drift",
  "concept drift",
  "behavioural drift",
  "behavioral drift",
  "retraining",
  "post-market monitoring",
  "continuous monitoring",
  "release readiness",

  // Deployment and operation
  "human oversight",
  "human-in-the-loop",
  "meaningful human review",
  "automated decision-making",
  "automated decision",
  "escalation path",
  "guardrails",
  "system prompt",
  "prompt injection",
  "jailbreak",
  "retrieval-augmented generation",
  "retrieval augmented generation",
  "grounding",
  "knowledge base",
  "fine-tuning",
  "hallucination",
  "confabulation",
  "general-purpose AI",
  "foundation model",
  "large language model",
  "shadow AI",
  "secondary use",
  "acceptable use",
  "authorized scope",
  "scope control",
  "defense-in-depth",
  "defence-in-depth",
  "third-party risk",
  "vendor risk",
  "incident response",
  "serious incident",
  "audit trail",
  "auditability",

  // Principles and roles
  "responsible AI",
  "AI governance",
  "algorithmic bias",
  "disparate impact",
  "proxy variable",
  "protected characteristic",
  "protected class",
  "explainability",
  "interpretability",
  "transparency",
  "accountability",
  "contestability",
  "fairness",
  "human-centricity",
  "cross-functional",
  "risk classification",
  "risk tolerance",
  "risk appetite",
  "systemic risk",
  "high-risk",
  "prohibited practice",
  "notified body",
  "CE marking",
  "provider",
  "deployer",
  "importer",
  "distributor",
  "controller",
  "processor",
];

/** Longest first, so multi-word terms are matched before their fragments. */
export const CONCEPT_TERMS_BY_LENGTH = [...CONCEPT_TERMS].sort(
  (a, b) => b.length - a.length,
);
